services:
  nb:
    build: .
    image: nb-cli
    ports:
      - "127.0.0.1:6789:6789"
    volumes:
      - ./notes:/notes
      - ./mathjax:/root/.nb/MathJax
    environment:
      - NB_MATHJAX_ENABLED=1
      - NB_DIR=/notes
      - HOME=/root
      - NB_SERVER_HOST=0.0.0.0
      - NB_SERVER_PORT=6789
    stdin_open: true
    tty: true
    working_dir: /notes
